# This is a basic workflow to help you get started with Actions
name: Q1

on: [push]

permissions:
  contents: write

jobs:
  ajout-readme:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copier README.md dans Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit and push the new file
        run: |
          git config --global user.name "astyell"
          git config --global user.email "etoiledeplante@gmail.com"
          git add Q1_archive_README.md
          git commit -m "Ajout Q1_archive_README.md"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
