# This is a basic workflow to help you get started with Actions

name: Q1

# Controls when the workflow will run
on: [push]
permissions:
  contents: write

jobs:
  ajout-readme:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - name: On fait un nouveau fichier
        run: cp README.md Q1_archive_README.md
    
      - name: On essaie de commit et push le fichier
        run: |
          git config --global user.name astyell
          git config --global user.email etoiledeplante@gmail.com
          git add Q1_archive_README.md
          git commit -m "test push de readme.md"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
